### Criar nova order
POST http://localhost:3000/freelas
Content-Type: application/json

{
    "nome": "Caio Occhi",
    "dt_nascimento": "1998-05-07",
    "pix": "27999157779",
    "telefone": "27999157779",
    "cpf": "14883667723",
    "funcao": "Garçom"
}

### Retornar todos os freelas
GET http://localhost:3000/freelas
Content-Type: application/json

### Excluir Freela pelo ID
POST http://localhost:3000/freelas/delete/6a14f01d480ca7566e183a85
Content-Type: application/json

### Alterar Freela pelo ID
PUT http://localhost:3000/freelas/update/6a14f733d0ead5f80d7adfb4
Content-Type: application/json

{
    "nome": "Caio Occhi",
    "funcao": "Chef"
}

### Criar usuário
POST http://localhost:3000/usuario/create
Content-Type: application/json

{
    "nome": "Caio Occhi",
    "email": "caioocchi5@gmail.com",
    "senha": "caio1234"
}

### Criar usuário
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "caioocchi5@gmail.com",
    "senha": "caio1234"
}

### Criar usuário
GET http://localhost:3000/auth/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2YTE1OTY5NDNjMzc0YzcwN2M3Mjk3ZjkiLCJlbWFpbCI6ImNhaW9vY2NoaTVAZ21haWwuY29tIiwiaWF0IjoxNzc5ODAwNTk5LCJleHAiOjE3ODA0MDUzOTl9.rVD7-DN-BhyRi8CD7dg5-Eb_ANq3KeA3nt7Y_u5Mn88
Content-Type: application/json