### Criar nova order
POST http://localhost:3000/freelas
Content-Type: application/json

{
    "nome": "Caio Occhi",
    "dt_nascimento": "1998-05-07",
    "pix": "27999157779",
    "telefone": "27999157779",
    "cpf": "14883667723",
    "funcao": "Garçom"
}

### Retornar todos os freelas
GET http://localhost:3000/freelas
Content-Type: application/json

### Excluir Freela pelo ID
POST http://localhost:3000/freelas/delete/6a14f01d480ca7566e183a85
Content-Type: application/json

### Alterar Freela pelo ID
PUT http://localhost:3000/freelas/update/6a14f733d0ead5f80d7adfb4
Content-Type: application/json

{
    "nome": "Caio Occhi",
    "funcao": "Chef"
}

### Criar usuário
POST http://localhost:3000/usuario/create
Content-Type: application/json

{
    "nome": "Caio Occhi",
    "email": "caioocchi5@gmail.com",
    "senha": "caio1234"
}

### Autentica usuário
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "caioocchi5@gmail.com",
    "senha": "caio1234"
}

### Criar usuário
GET http://localhost:3000/auth/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2YTE1OTY5NDNjMzc0YzcwN2M3Mjk3ZjkiLCJlbWFpbCI6ImNhaW9vY2NoaTVAZ21haWwuY29tIiwiaWF0IjoxNzc5ODAwNTk5LCJleHAiOjE3ODA0MDUzOTl9.rVD7-DN-BhyRi8CD7dg5-Eb_ANq3KeA3nt7Y_u5Mn88
Content-Type: application/json

### Retornar todos os produtos
GET http://localhost:3000/produto

### Retornar produto por "categoria"
GET http://localhost:3000/produto/proteina

### Retornar evento por ID
GET http://localhost:3000/eventos/6a1c4ed69950b51d5a0f2cfd

### Excluir evento
POST http://localhost:3000/eventos/delete/6a1c4ed69950b51d5a0f2cfd

### Criar evento
POST http://localhost:3000/eventos
Content-Type: application/json

{
    "nome_contratante": "Caio Occhi",
    "endereco": {
        "cep": "29102-035",
        "logradouro": "Avenida Saturnino Rangel Mauro",
        "numero": "3100",
        "complemento": "apto 1003",
        "bairro": "Praia de Itaparica",
        "cidade": "Vila Velha"
    },
    "data": "2026-08-15",
    "hora": "12:00",
    "qtde_pessoas": 50,
    "observacoes": "",
    "itens": [
        {
        "nome": "Ancho",
        "categoria": "proteina",
        "quantidade": 10,
        "unidade": "kg"
        },
        {
        "nome": "Picanha",
        "categoria": "proteina",
        "quantidade": 10,
        "unidade": "kg"
        },
        {
        "nome": "Bandeja preta",
        "categoria": "limpeza_identidade",
        "quantidade": 1,
        "unidade": "un"
        },
        {
        "nome": "Perfex",
        "categoria": "limpeza_identidade",
        "quantidade": 2,
        "unidade": "un"
        },
        {
        "nome": "Pano de prato",
        "categoria": "limpeza_identidade",
        "quantidade": 4,
        "unidade": "un"
        },
        {
        "nome": "Mesa",
        "categoria": "servico_mesa",
        "quantidade": 2,
        "unidade": "un"
        },
        {
        "nome": "Toalha de mesa",
        "categoria": "servico_mesa",
        "quantidade": 2,
        "unidade": "un"
        },
        {
        "nome": "Feijão tropeiro",
        "categoria": "acompanhamento",
        "quantidade": 5,
        "unidade": "kg"
        },
        {
        "nome": "Arroz",
        "categoria": "acompanhamento",
        "quantidade": 5,
        "unidade": "kg"
        },
        {
        "nome": "Vinagrete",
        "categoria": "acompanhamento",
        "quantidade": 2,
        "unidade": "kg"
        },
        {
        "nome": "Farofa",
        "categoria": "acompanhamento",
        "quantidade": 1,
        "unidade": "kg"
        },
        {
        "nome": "Mix de folhas",
        "categoria": "acompanhamento",
        "quantidade": 0.5,
        "unidade": "kg"
        }
    ]
}